### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

### ISSUE THREAD

**Issue by wjhebin** [VikParuchuri/surya#65]
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

File "C:\ProgramData\Anaconda31\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "C:\ProgramData\Anaconda31\Lib\site-packages\ocr_app.py", line 7, in <module>
    from surya.detection import batch_text_detection
File "C:\ProgramData\Anaconda31\lib\site-packages\surya\detection.py", line 7, in <module>
    from surya.postprocessing.heatmap import get_and_clean_boxes
File "C:\ProgramData\Anaconda31\lib\site-packages\surya\postprocessing\heatmap.py", line 8, in <module>
    from surya.postprocessing.fonts import get_font_path
File "C:\ProgramData\Anaconda31\lib\site-packages\surya\postprocessing\fonts.py", line 8, in <module>
    def get_font_path(langs: List[str] | None = None) -> str:

    W11, Python 3.12.2

 What should I do about this problem?

**Comment by VikParuchuri** [comment]
This should be fixed now

**Comment by psungho** [comment]
@VikParuchuri  Still not fixed... on the python version at least

**Comment by bojrick** [comment]
2025-01-25 21:28:59.012 Uncaught app execution
Traceback (most recent call last):
  File "/home/bojrick/surya-ocr-test/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/home/bojrick/surya-ocr-test/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/bojrick/surya-ocr-test/venv/lib/python3.9/site-packages/ocr_app.py", line 8, in <module>
    from surya.detection import batch_text_detection
  File "/home/bojrick/surya-ocr-test/venv/lib/python3.9/site-packages/surya/detection.py", line 8, in <module>
    from surya.postprocessing.heatmap import get_and_clean_boxes
  File "/home/bojrick/surya-ocr-test/venv/lib/python3.9/site-packages/surya/postprocessing/heatmap.py", line 10, in <module>
    from surya.schema import PolygonBox
  File "/home/bojrick/surya-ocr-test/venv/lib/python3.9/site-packages/surya/schema.py", line 157, in <module>
    class OCRResult(BaseModel):
  File "/home/bojrick/surya-ocr-test/venv/lib/python3.9/site-packages/surya/schema.py", line 159, in OCRResult
    languages: List[str] | None = None
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'
2025-01-25 21:28:59.215 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

yes I think similar issue I am facing when running surya_gui
